@baseUrl = http://localhost:8080


### get all tasks

GET {{baseUrl}}/tasks HTTP/1.1
Authorization: {{TOKEN}}

### get all task without TOKEN

GET {{baseUrl}}/tasks HTTP/1.1

### add new task

POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "title": "xin chao"
}

### add new task missing TOKEN

POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Nhom nhom"
}

### add new task missing title

POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{}

### add new task empty title

POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "title": ""
}

### add new task blank title

POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "title": "   "
}

### add new task title wrong datatype

POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "title": true
}

### edit tasks missing field

PATCH {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{}

### edit task title

PATCH {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "title": "Learn Golang Vip Pro"
}

### edit task title with wrong datatype

PATCH {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "title": true
}

### edit task title missing Authorization

PATCH {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Learn Golang Vip Pro"
}

### edit task title with not exist user

PATCH {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: 100

{
  "title": "Learn Golang Vip Pro"
}

### edit atask title with not exist task

PATCH {{baseUrl}}/tasks/100 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "title": "Learn Golang Vip Pro"
}

### edit task empty title

PATCH {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "title": ""
}

### edit task blank title

PATCH {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "title": "   "
}

### edit task status

PATCH {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "completed": true
}

### edit task status wit wrong datatype

PATCH {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "completed": "true"
}

### edit task title and status

PATCH {{baseUrl}}/tasks/3 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "title": "Learn Go net/http",
  "completed": true
}

### edit task owned by another user

PATCH {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: 2

{
  "title": "Hacked title"
}

### delete task

DELETE {{baseUrl}}/tasks/1 HTTP/1.1
Authorization: {{TOKEN}}

### delete task missing Authorization

DELETE {{baseUrl}}/tasks/1 HTTP/1.1

### delete task not exist

DELETE {{baseUrl}}/tasks/100 HTTP/1.1
Authorization: {{TOKEN}}

### delete task owned by another user

DELETE {{baseUrl}}/tasks/1 HTTP/1.1
Authorization: {{OTHER_TOKEN}}

### method not allowed on tasks

PUT {{baseUrl}}/tasks HTTP/1.1
Authorization: {{TOKEN}}

### method not allowed on task detail

POST {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "title": "Invalid"
}
